#ifndef _MAZE_PROBABILITIES_H
#define _MAZE_PROBABILITIES_H

#define MAZE_PROBA_MOVE_GLOBAL_RATIO 1.0f
#define MAZE_PROBA_MOVE_FAIL_RATIO 0.1f
#define MAZE_PROBA_MOVE_SUCCESS_RATIO (1.0f - MAZE_PROBA_MOVE_FAIL_RATIO)

#endif
