#ifndef _PROBABILITIES_H
#define _PROBABILITIES_H

#define MAZE_PROBABILITIES_MOVE_UP 0.25f
#define MAZE_PROBABILITIES_MOVE_DOWN 0.25f
#define MAZE_PROBABILITIES_MOVE_LEFT 0.25f
#define MAZE_PROBABILITIES_MOVE_RIGHT 0.25f

#endif
